"""从浏览器导出 cookies 工具

使用 Playwright 从浏览器导出 cookies，保存为 Netscape 格式的 cookies.txt 文件。
"""

import asyncio
import sys
from pathlib import Path
from typing import Optional

try:
    from playwright.async_api import async_playwright, Browser, BrowserContext
except ImportError:
    print("错误: 需要安装 playwright")
    print("请运行: pip install playwright")
    print("然后运行: playwright install chromium")
    sys.exit(1)


def format_cookie_for_netscape(cookie: dict) -> str:
    """
    将 cookie 字典转换为 Netscape 格式的字符串
    
    Netscape 格式：
    domain	flag	path	secure	expiration	name	value
    
    其中：
    - domain: cookie 的域名（如 .bilibili.com）
    - flag: TRUE/FALSE，表示是否对所有子域名有效
    - path: cookie 的路径（通常是 /）
    - secure: TRUE/FALSE，表示是否只在 HTTPS 下发送
    - expiration: Unix 时间戳（秒），0 表示会话 cookie
    - name: cookie 名称
    - value: cookie 值
    """
    domain = cookie.get("domain", "")
    # 如果 domain 以 . 开头，flag 为 TRUE
    flag = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path", "/")
    secure = "TRUE" if cookie.get("secure", False) else "FALSE"
    
    # 处理过期时间
    expires = cookie.get("expires", -1)
    if expires == -1:
        expiration = "0"  # 会话 cookie
    else:
        expiration = str(int(expires))
    
    name = cookie.get("name", "")
    value = cookie.get("value", "")
    
    return f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"


async def export_cookies_from_browser(
    url: str,
    output_file: str,
    browser_type: str = "chromium",
    headless: bool = False,
    wait_time: int = 3,
) -> bool:
    """
    从浏览器导出 cookies
    
    Args:
        url: 要访问的 URL（用于获取该域名的 cookies）
        output_file: 输出文件路径
        browser_type: 浏览器类型（chromium, firefox, webkit）
        headless: 是否无头模式
        wait_time: 等待时间（秒），用于等待页面加载和登录
        
    Returns:
        是否成功
    """
    async with async_playwright() as p:
        # 启动浏览器
        if browser_type == "chromium":
            browser = await p.chromium.launch(headless=headless)
        elif browser_type == "firefox":
            browser = await p.firefox.launch(headless=headless)
        elif browser_type == "webkit":
            browser = await p.webkit.launch(headless=headless)
        else:
            print(f"错误: 不支持的浏览器类型: {browser_type}")
            return False
        
        try:
            # 创建上下文
            context = await browser.new_context()
            page = await context.new_page()
            
            print(f"正在打开: {url}")
            print(f"请在该页面完成登录（如果需要），等待 {wait_time} 秒后自动导出 cookies...")
            
            # 访问 URL
            await page.goto(url, wait_until="networkidle")
            
            # 等待用户登录
            await asyncio.sleep(wait_time)
            
            # 获取 cookies
            cookies = await context.cookies()
            
            if not cookies:
                print("警告: 没有获取到任何 cookies")
                return False
            
            # 写入文件
            output_path = Path(output_file)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, "w", encoding="utf-8") as f:
                # 写入 Netscape 格式的头部
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by multi_video_dl cookie_fetcher\n")
                f.write("# <domain>\t<flag>\t<path>\t<secure>\t<expiration>\t<name>\t<value>\n\n")
                
                # 写入 cookies
                for cookie in cookies:
                    line = format_cookie_for_netscape(cookie)
                    f.write(line + "\n")
            
            print(f"成功导出 {len(cookies)} 个 cookies 到: {output_path}")
            return True
            
        finally:
            await browser.close()


def main():
    """命令行入口"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="从浏览器导出 cookies 为 Netscape 格式",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # 导出 B 站 cookies
  python tools/cookie_fetcher.py https://www.bilibili.com cookies.txt
  
  # 使用 Firefox 浏览器
  python tools/cookie_fetcher.py https://www.bilibili.com cookies.txt --browser firefox
  
  # 无头模式（后台运行）
  python tools/cookie_fetcher.py https://www.bilibili.com cookies.txt --headless
  
  # 等待 10 秒（给更多时间登录）
  python tools/cookie_fetcher.py https://www.bilibili.com cookies.txt --wait 10
        """,
    )
    
    parser.add_argument(
        "url",
        help="要访问的 URL（用于获取该域名的 cookies）",
    )
    parser.add_argument(
        "output",
        help="输出文件路径（cookies.txt）",
    )
    parser.add_argument(
        "--browser",
        choices=["chromium", "firefox", "webkit"],
        default="chromium",
        help="浏览器类型（默认: chromium）",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="无头模式（后台运行，不显示浏览器窗口）",
    )
    parser.add_argument(
        "--wait",
        type=int,
        default=3,
        help="等待时间（秒），用于等待页面加载和登录（默认: 3）",
    )
    
    args = parser.parse_args()
    
    # 运行异步函数
    success = asyncio.run(
        export_cookies_from_browser(
            url=args.url,
            output_file=args.output,
            browser_type=args.browser,
            headless=args.headless,
            wait_time=args.wait,
        )
    )
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
